// Code generated by baton-sdk. DO NOT EDIT!!!
package config

import "reflect" 

type Eks struct {
	ExternalId string `mapstructure:"external-id"`
	GlobalAccessKeyId string `mapstructure:"global-access-key-id"`
	GlobalBindingExternalId string `mapstructure:"global-binding-external-id"`
	GlobalRegion string `mapstructure:"global-region"`
	GlobalRoleArn string `mapstructure:"global-role-arn"`
	GlobalSecretAccessKey string `mapstructure:"global-secret-access-key"`
	RoleArn string `mapstructure:"role-arn"`
	UseAssume bool `mapstructure:"use-assume"`
	EksAccessKey string `mapstructure:"eks-access-key"`
	EksSecretAccessKey string `mapstructure:"eks-secret-access-key"`
	EksRegion string `mapstructure:"eks-region"`
	EksAssumeRoleArn string `mapstructure:"eks-assume-role-arn"`
	EksClusterName string `mapstructure:"eks-cluster-name"`
}

func (c* Eks) findFieldByTag(tagValue string) (any, bool) {
	v := reflect.ValueOf(c).Elem() // Dereference pointer to struct
	t := v.Type()

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("mapstructure")

		if tag == tagValue {
			return v.Field(i).Interface(), true
		}
	}
	return nil, false
}

func (c *Eks) GetStringSlice(fieldName string) []string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return []string{}
	}
	t, ok := v.([]string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Eks) GetString(fieldName string) string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return ""
	}
	t, ok := v.(string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Eks) GetInt(fieldName string) int {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return 0
	}
	t, ok := v.(int)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Eks) GetBool(fieldName string) bool {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return false
	}
	t, ok := v.(bool)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Eks) GetStringMap(fieldName string) map[string]any {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return map[string]any{}
	}
	t, ok := v.(map[string]any)
	if !ok {
		panic("wrong type")
	}
	return t
}
